# Generated by Django 3.2.3 on 2021-05-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='tutors',
            field=models.ManyToManyField(to='app.Tutor'),
        ),
    ]
