# Generated by Django 3.2.3 on 2021-05-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210529_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='day',
            field=models.CharField(choices=[('monday', 'понеділок'), ('tuesday', 'вівторок'), ('wednesday', 'середа'), ('thursday', 'четверг'), ('friday', 'пятниця')], default='', max_length=20),
        ),
    ]
