# Generated by Django 3.2.3 on 2021-05-29 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_lesson_tutors'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.group'),
        ),
    ]
