# Generated by Django 3.2.3 on 2021-05-29 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_day_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='name',
        ),
    ]
