# Generated by Django 3.2.3 on 2021-05-29 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_week_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'verbose_name': 'День', 'verbose_name_plural': 'Дні'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Група', 'verbose_name_plural': 'Групи'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предмети'},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name': 'Викладач', 'verbose_name_plural': 'Викладачі'},
        ),
        migrations.AlterModelOptions(
            name='week',
            options={'verbose_name': 'Тиждень', 'verbose_name_plural': 'Тиждні'},
        ),
    ]
