# Generated by Django 3.2.3 on 2021-05-29 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('app', '0004_remove_day_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предмети',
            },
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.RemoveField(
            model_name='day',
            name='day',
        ),
        migrations.RemoveField(
            model_name='day',
            name='lesson_1',
        ),
        migrations.RemoveField(
            model_name='day',
            name='lesson_2',
        ),
        migrations.RemoveField(
            model_name='day',
            name='lesson_3',
        ),
        migrations.RemoveField(
            model_name='day',
            name='lesson_4',
        ),
        migrations.RemoveField(
            model_name='day',
            name='lesson_5',
        ),
        migrations.RemoveField(
            model_name='day',
            name='tutor_1',
        ),
        migrations.RemoveField(
            model_name='day',
            name='tutor_2',
        ),
        migrations.RemoveField(
            model_name='day',
            name='tutor_3',
        ),
        migrations.RemoveField(
            model_name='day',
            name='tutor_4',
        ),
        migrations.RemoveField(
            model_name='day',
            name='tutor_5',
        ),
        migrations.RemoveField(
            model_name='day',
            name='week',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='tutors',
        ),
        migrations.RemoveField(
            model_name='week',
            name='group',
        ),
        migrations.AddField(
            model_name='day',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lesson',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.day'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.group'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.tutor'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.week'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subject'),
        ),
    ]
