# Generated by Django 3.2.3 on 2021-05-29 17:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfTheWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_weekday', models.CharField(choices=[('Monday', 'Понеділок'), ('Tuesday', 'Вівторок'), ('Wednesday', 'Середа'), ('Thursday', 'Четвер'), ('Friday', "П'ятниця"), ('Saturday', 'Субота'), ('Sunday', 'Неділя')], max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Name', max_length=20)),
                ('last_name', models.CharField(default='Surname', max_length=20)),
                ('zoom_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_week', models.CharField(choices=[('red', 'Червона'), ('blue', 'Синя')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.TextField(max_length=200)),
                ('position', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('group_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='timetable.group')),
                ('subject_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='timetable.subject')),
                ('tutor_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='timetable.tutor')),
                ('week_day_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='timetable.dayoftheweek')),
                ('week_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='timetable.week')),
            ],
        ),
    ]
