# Generated by Django 3.2.3 on 2021-05-29 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210529_1724'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='tutor_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='account.tutor'),
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
