# Generated by Django 3.2.3 on 2021-05-29 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20210529_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayoftheweek',
            options={'verbose_name': 'День тижня', 'verbose_name_plural': 'Дні тижня'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Група', 'verbose_name_plural': 'Групи'},
        ),
        migrations.AlterModelOptions(
            name='pair',
            options={'verbose_name': 'Пара', 'verbose_name_plural': 'Пари'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предмети'},
        ),
        migrations.AlterModelOptions(
            name='week',
            options={'verbose_name': 'Тиждень', 'verbose_name_plural': 'Тижні'},
        ),
    ]
