# Generated by Django 3.2.3 on 2021-05-29 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20210529_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayoftheweek',
            name='week_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='week_days', to='timetable.week'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='week',
            name='group_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='timetable.group'),
            preserve_default=False,
        ),
    ]
